name: LLVM Code Coverage

on:
  push:
    branches:
      - aarch64_idiom

jobs:
  code-coverage:
    name: Generate Code Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout LLVM Repository
        uses: actions/checkout@v2
        with:
          ref: aarch64_idiom

      - name: Install LLVM project build dependency
        run: |
          sudo apt-get install llvm
          sudo apt-get install clang
          sudo apt-get install lld
          sudo apt-get install cmake
          sudo apt-get install ninja-build
                  
      - name: Build LLVM project
        run: |
          mkdir build
          cd build
      
      - name: Run the patch-based code coverage tool
        run: |
          cp llvm/utils/git-check-coverage.py .
          python3 llvm/utils/git-check-coverage.py -b build -c c160c3c65107d5b1b2993972bce903304d4860e6 bin/opt llvm/test
